// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sokfvqtgpbeybjifaywh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNva2Z2cXRncGJleWJqaWZheXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Nzc2MTUsImV4cCI6MjA2MDU1MzYxNX0.TltVuH6rtd7UFbJgyStevuXVoC3eTUTZuUOHrzP3Dw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);